### ISSUE TITLE
can't disable chromatic aberration

### ISSUE THREAD

**Issue by ultrawiredx** [aliasIsolation/aliasIsolation#17]
![screen](https://user-images.githubusercontent.com/34123505/33421145-ec1ebe60-d58f-11e7-87a2-309e011b1ef3.jpg)

as you can see, all the other adjustments have taken effect like removing the bloom entirely but I just can't diasble the chromatic aberration no matter what I do. 

I even disable it without the cinematic tool, just the plain GuI launcher which allows to choose the levels of the sharpness and chromatic aberration and still doesn't work. It does the sharpening job though.

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
@ultrawiredx 

I totally get you, I used to think this effect was really neat for the art style, after experiencing horribly flawed prescription glasses, defective in respects to all others I had owned, I now find chromatic abberation to be extremely bothersome. 

I have to say, it is as disorientating in game (probably intended) as it is in real life. The only way I could stand my vision this way is having been born and never knowing it was not correct. Worst self birthday present ever, worst glasses ever.

Would be lovely if someone could find a solution to this issue. Thanks! 😞 

Happy new year! :tada:
