### ISSUE TITLE
Mod crash

### ISSUE THREAD

**Issue by RioIT1911** [aliasIsolation/aliasIsolation#21]
first time i downloaded this mod, it worked very good... but after a few days, it stopped to work :(

When i run (as administrator) it give me this error:

---------------------------
Fatal error
---------------------------
A fatal error was caught by Alias Isolation, and the current process will terminate.
A crash dump has been written to C:\Users\VINCEN~1\AppData\Local\Temp\aliasIsolationCrashDump.dmp.
Press Ctrl+C to copy the contents of this message to the clipboard.

aliasIsolation_hookableOverlayRender
D3D11CreateDevice
D3D11CreateDevice
D3DKMTQueryResourceInfo
D3DKMTQueryResourceInfo
DXGIGetDebugInterface1
DXGID3D10CreateLayeredDevice
CompatString
CompatString
 ?? 
 ?? 
 ?? 
CompatString
DXGIGetDebugInterface1
DXGIGetDebugInterface1
D3DKMTWaitForVerticalBlankEvent
D3D11CreateDeviceAndSwapChain
aliasIsolation_hookableOverlayRender
 ?? 
 ?? 
 ?? 
BaseThreadInitThunk
RtlValidSecurityDescriptor
RtlValidSecurityDescriptor

---------------------------
OK   
---------------------------

what can i do? sorry for bad english

**Comment by Torrespain** [comment]
I had the same problem. To solve it I detached everything, then entered in the game and in video settings I selected windowed full screen (the game still runs in full screen) end then run the aliasIsolationInjectorGui.exe as administrator.
