### ISSUE TITLE
Injector Gui not working

### ISSUE THREAD

**Issue by ayo-daniel** [aliasIsolation/aliasIsolation#48]
I am having trouble launching the injector GUI. When I click on 'Launch', nothing happens. I see the blue circle on my cursor for less than a second and then it disappears. I have already closed Steam and set up the correct path in the injector settings. I am not sure what else to do. Does anybody have a fix?

**Comment by tonyissa** [comment]
I too am having this issue

**Comment by tonyissa** [comment]
> I too am having this issue

Okay I figured it out, make sure you run AI.exe as admin. To be fair I did this with the RyanJGray v1.1.1 fork and it worked, I'm not using this version of the mod.

**Comment by RyanJGray** [comment]
The injector GUIs are pretty old and I had a hard time trying to maintain them, I'm going to look into why admin is needed for my fork to work.

Eventually the updated version of this mod in my fork will be merged into this repository, and become the next official release.

There's still some issues with my fork that I want to sort out before that happens, though.

**Comment by Eye29** [comment]
Not working for me also
