### ISSUE TITLE
bug: Can't see the GUI after pressing delete on fresh install of the game

### ISSUE THREAD

**Issue by hextorio** [aliasIsolation/aliasIsolation#52]
**Describe the bug**
I cannot see the GUI to tune sharpening and CA. Only cursor appears after I press Delete. However the antialiasing work just fine.

**Setup details**
 - Game store: Steam
 - OS version: latest Windows 11
 - GPU model: RTX 4090
 - GPU driver and version: latest
 - Mod version: latest

Resolution 3840x2160

**Comment by RyanJGray** [comment]
Hey, thanks for the report!

Does this happen only after you change the resolution of the game, or does the menu just not display at all for you?

**Comment by hextorio** [comment]
I open the game and load the save without changing any settings and I still cannot see the GUI. Let me check on other resolutions maybe.

**Comment by hextorio** [comment]
Found the problem. Once I closed MSI Afterburner and Rivatuner that were open in the background and re-launched the game the GUI now works fine.

**Comment by RyanJGray** [comment]
Do they render their own overlays? The way Alias hooks into the game for rendering the UI is probably not compatible with other overlays, which would make sense

**Comment by hextorio** [comment]
Indeed they do, like on the attached screenshot
![maxresdefault](https://github.com/user-attachments/assets/081e0534-2a32-4437-8fcc-2d0c3a4e6ca0)
