### ISSUE TITLE
bug: Shadows appear low quality

### ISSUE THREAD

**Issue by svoltmer** [aliasIsolation/aliasIsolation#58]
**Describe the bug**
After extracting the files into the main Alien Isolation directory, ensuring that the mods are in the "mods" folder, setting Anti-aliasing to SMAA T1xx, Chromatic Aberration to disabled, and Motion blur to enabled, after reaching the station the shadows are low quality some dark rooms even with the shadow maps set to the highest settings.

**How to reproduce**
After extracting the files into the main Alien Isolation directory, ensuring that the mods are in the "mods" folder, setting Anti-aliasing to SMAA T1xx, Chromatic Aberration to disabled, and Motion blur to enabled, shadow maps appear low quality in some dimly lit situations.

**Expected behavior**
High quality shadow maps.

**Screenshots**
![image](https://github.com/user-attachments/assets/04dfbfdc-c761-478e-8040-20235f3be0e8)

**Setup details**
 - Game store: Steam
 - OS version: Windows 11 Pro 23H2 
 - GPU model: NVIDIA RTX 4070
 - GPU driver and version: NVIDIA 565.90

 - Mod version: v1.2.0

**Additional context**
(Add any other context about the problem here)

**Comment by RyanJGray** [comment]
Interesting, and the shadow maps become high quality again with Alias removed?

I'll take a look into this code-side

**Comment by svoltmer** [comment]
I tried to disable the mod using Ctrl+Del at startup, but it just rapidly cycles the GUID for the mod sharpness on and off. I'll have to uninstall/reinstall the game when I have some free time, to test whether the shadow maps become high quality again with Alias removed.

**Comment by RyanJGray** [comment]
Ctrl+Del will disable the mod, but you only need to press it once, you don't need to hold it down.

You can also disable the mod by moving `aliasIsolation.asi` to another folder

**Comment by RyanJGray** [comment]
Ctrl+Del will disable the mod, but you only need to press it once, you don't need to hold it down.

You can also disable the mod by moving `aliasIsolation.asi` to another folder

**Comment by svoltmer** [comment]
I disabled the aliasIsolation mod by moving it to a different folder, and the issue still persists, so it must not be the mod. I am using the Isolation Tweaker though, so I suppose it could be that.

**Comment by RyanJGray** [comment]
It could be, I don't have any experience with that specific tweaker, it might be changing the shadow map settings in a way that breaks the engine's logic that interprets that setting
